package me.noramibu.itemeditor.util;

enum RawSlotType {
    OBJECT_KEY,
    VALUE_BOOLEAN,
    VALUE_INT,
    VALUE_FLOAT,
    VALUE_ID_EFFECT,
    VALUE_ID_ENCHANTMENT,
    VALUE_ID_ITEM,
    VALUE_ID_ENTITY,
    VALUE_ID_COMPONENT,
    VALUE_ID_DAMAGE_TYPE,
    VALUE_ID_POTION,
    VALUE_ID_BANNER_PATTERN,
    VALUE_ID_BLOCK_ENTITY,
    VALUE_ID_TRIM_MATERIAL,
    VALUE_ID_TRIM_PATTERN,
    VALUE_ID_SOUND,
    VALUE_ID_ATTRIBUTE,
    VALUE_STRING,
    VALUE_UNKNOWN
}
